export const availableStocks = {
  tataMotors: "TATAMOTORS",
  tataSteel: "TATASTEEL",
  itc: "ITC",
  hdfcLife: "HDFCLIFE",
  kfinTech: "KFINTECH",
  laOplaRG: "LAOPALA",
  HDFCBANK: "HDFCBANK",
  UPL: "UPL",
  KOTAKBANK: "KOTAKBANK",
  latentView: "LATENTVIEW",
  ZOMATO: "ZOMATO",
  BHEL: "BHEL",
  RECLTD: "RECLTD",
  BANKBARODA: "BANKBARODA",
  JSWENERGY: "JSWENERGY",
  CANBK: "CANBK",
  AMBUJACEM: "AMBUJACEM",
  VBL: "VBL",
  ZEEL: "ZEEL",
  VEDL: "VEDL",
  INDHOTEL: "INDHOTEL",
  DLF: "DLF",
  SUNTV: "SUNTV",
  POONAWALLA: "POONAWALLA",
  INDIANB: "INDIANB",
  ABFRL: "ABFRL",
  DEVYANI: "DEVYANI",
};

export const bestStockPresets = {
  ...Object.values(availableStocks).reduce((acc, curr) => {
    acc[curr] = {};
    return acc;
  }, {}),
  [availableStocks.tataMotors]: {
    decisionMakingPoints: 3,
    additionalIndicators: {
      willR: false,
      mfi: false,
      cci: false,
      trend: true,
      stochastic: true,
      vwap: true,
      psar: false,
    },
    vPointOffset: 7,
  },
  [availableStocks.tataSteel]: {
    decisionMakingPoints: 3,
    additionalIndicators: {
      willR: false,
      mfi: false,
      trend: true,
      cci: false,
      stochastic: false,
      vwap: false,
      psar: false,
    },
    useSupportResistances: true,
    vPointOffset: 8,
  },
  [availableStocks.hdfcLife]: {
    additionalIndicators: {
      willR: false,
      mfi: false,
      trend: true,
      cci: false,
      stochastic: false,
      vwap: false,
      psar: false,
    },
    vPointOffset: 6,
    bollingerBandStdDev: 2,
  },
  [availableStocks.INDHOTEL]: {
    vPointOffset: 12,
  },
  [availableStocks.DEVYANI]: {
    vPointOffset: 4,
  },
  [availableStocks.ABFRL]: {
    additionalIndicators: {
      willR: false,
      mfi: false,
      trend: false,
      cci: false,
      stochastic: false,
      vwap: false,
      psar: false,
    },
    vPointOffset: 7,
  },
  [availableStocks.INDIANB]: {
    vPointOffset: 7,
  },
  [availableStocks.POONAWALLA]: {
    vPointOffset: 6,
  },
  [availableStocks.SUNTV]: {
    vPointOffset: 14,
  },
  [availableStocks.INDHOTEL]: {
    vPointOffset: 12,
  },
  [availableStocks.VEDL]: {
    vPointOffset: 10,
    additionalIndicators: {
      willR: false,
      mfi: false,
      trend: true,
      cci: false,
      stochastic: true,
      vwap: false,
      psar: false,
    },
  },
  [availableStocks.DLF]: {
    vPointOffset: 8,
    additionalIndicators: {
      willR: false,
      mfi: false,
      trend: false,
      cci: false,
      stochastic: true,
      vwap: false,
      psar: false,
    },
  },
  [availableStocks.ZEEL]: {
    decisionMakingPoints: 3,
    additionalIndicators: {
      willR: false,
      mfi: true,
      trend: true,
      cci: false,
      stochastic: false,
      vwap: false,
      psar: false,
    },
    vPointOffset: 8,
    bollingerBandStdDev: 2,
    rsiLow: 40,
    rsiHigh: 80,
  },
  [availableStocks.VBL]: {
    vPointOffset: 6,
    additionalIndicators: {
      willR: false,
      mfi: false,
      trend: true,
      cci: false,
      stochastic: false,
      vwap: false,
      psar: false,
    },
  },
  [availableStocks.CANBK]: {
    vPointOffset: 10,
    additionalIndicators: {
      willR: false,
      mfi: false,
      trend: false,
      cci: false,
      stochastic: true,
      vwap: false,
      psar: false,
    },
  },
  [availableStocks.itc]: {
    decisionMakingPoints: 3,
    additionalIndicators: {
      willR: false,
      mfi: false,
      trend: true,
      cci: false,
      stochastic: true,
      vwap: true,
      psar: false,
    },
    useSupportResistances: true,
    vPointOffset: 10,
  },
  [availableStocks.BHEL]: {
    useSupportResistances: false,
    decisionMakingPoints: 4,
    additionalIndicators: {
      willR: false,
      mfi: false,
      trend: true,
      cci: false,
      stochastic: true,
      vwap: true,
      psar: false,
    },
    vPointOffset: 9,
  },
  [availableStocks.DEVYANI]: {
    decisionMakingPoints: 4,
    additionalIndicators: {
      willR: false,
      mfi: false,
      trend: true,
      cci: false,
      stochastic: true,
      vwap: true,
      psar: false,
    },
    useSupportResistances: true,
    vPointOffset: 5,
  },
  [availableStocks.RECLTD]: {
    decisionMakingPoints: 4,
    additionalIndicators: {
      willR: false,
      mfi: false,
      trend: true,
      cci: false,
      stochastic: true,
      vwap: true,
      psar: false,
    },
    useSupportResistances: false,
    vPointOffset: 10,
  },
  [availableStocks.BANKBARODA]: {
    decisionMakingPoints: 4,
    additionalIndicators: {
      willR: false,
      mfi: false,
      trend: true,
      cci: false,
      stochastic: true,
      vwap: true,
      psar: false,
    },
    useSupportResistances: false,
    vPointOffset: 10,
  },
  [availableStocks.HDFCBANK]: {
    decisionMakingPoints: 4,
    additionalIndicators: {
      willR: false,
      mfi: false,
      trend: true,
      cci: false,
      stochastic: true,
      vwap: true,
      psar: false,
    },
    useSupportResistances: false,
    vPointOffset: 12,
  },
};
